# Register Machines Info to PVE Machines YAML
- name: Save The Selected Machine to a YAML file
  copy:
    content: "{{ vm_file | to_yaml }}"
    dest: ./PVE_Machines.yaml
  delegate_to: localhost
  become: false

# Create SSH Key
- name: Copy The SSH Key
  ansible.builtin.copy:
    content: "{{ ssh_key }}"
    dest: /tmp/ansible_ssh_key
    mode: '0600'

# Remove Previous report File
- name: Remove report.log if it exists
  ansible.builtin.file:
    path: ./report.log
    state: absent  # Remove the file if it exists
  delegate_to: localhost
  become: false

# Create new report file
- name: Create a file if it does not exist
  ansible.builtin.file:
    path: ./report.log  # Specify the path to the file
    state: touch  # This will create the file if it does not exist
  delegate_to: localhost
  become: false